# If you only want to install xiaozhi-server lightly, only use the local configuration file, you don't need to pay attention to this file, and you don't need to change anything about this file 
# If you want to get the configuration from the manager-api, look below: 
# Please copy this file to the xiaozhi-server/data directory, if there is no data directory, please create one and name the copied past file as.config.yaml 
# Note If the data directory has a.config.yaml file, please delete it first 
# Start manager-api and manager-web first, register an account, and the first registered account is an administrator 
# To use the administrator, go to the Parameter Management page, find server.secret, copy it to the parameter value, and note that server.secret will change every time it is deployed from scratch 
# Open the.config.yaml file in this data directory and change the manager-api.secret to the server.secret copied just now 

server: ip: 0.0.0.0 
port: 8000 

# A port for the HTTP service for the visual analysis interface 

http_port: 8003 
# Visual analysis interface address 
# The interface address of the visual analysis sent to the device 
# If you follow the default writing method below, the system will automatically generate a visual identification address and output it in the startup log, which you can directly access and confirm with the browser 
# Not necessarily accurate when you deploy with docker or use public network deployment (using SSL, domain name). 
# So if you use docker to deploy, set the vision_explain to the LAN address 
# If you use a public network deployment, set the vision_explain to a public network address 

vision_explain: http:// your IP or domain name: port number/mcp/vision/explain 
manager-api: # The address of your manager-api is preferably a LAN IP 

# If deploying using docker, please use the http://xiaozhi-esp32-server-web:8002/xiaozhi 

url: http://127.0.0.1:8002/xiaozhi 
# The token of your manager-api is the server.secret that was copied just now 

secret: Your server.secret value 
# Default system prompt template file 
prompt_template:agent-base-prompt.txt
